### ISSUE TITLE
Comment Node Bug

### ISSUE THREAD

**Issue by Neuffexx** [blockout22/OverwatchVisualScripting#12]
I have recently noticed more and more that the comment node's Name doesnt stay in one line and is borken apart into multiple lines.
I understand why this is something that exists in case its sized to small, to auto line break.
But what makes me thing its a bug is that the comment boxes seem to require me to make them bigger and bigger just to fit little text into one line.

For example, I have two instances where I create a new comment, but each one has different 'minimum size's just to keep things in one line:
I created this comment first:

https://github.com/blockout22/OverwatchVisualScripting/assets/63469833/1a27017e-488e-4665-b8d7-15b15ac29e6f

Then this one:

https://github.com/blockout22/OverwatchVisualScripting/assets/63469833/cdc1d6e5-06f7-49d5-99ee-b1b9192debe0

Where the second comment node has less text than the first but somehow requires a wider size to fit it into a single line?

**Comment by blockout22** [comment]
9d640c8 nice find, I have fixed it 

it had something todo with the position rather than the size so the further to the right the comment in the graph the bigger you had to make the node

**Comment by Neuffexx** [comment]
Ah I see, thanks!
