### ISSUE TITLE
Nodes/feature request

### ISSUE THREAD

**Issue by millionart** [blockout22/OverwatchVisualScripting#2]
Nodes:

- Modify Player Score
- Set Player Allowed Heroes 
- Filtered Array
- Skip If

Feature:

- Description textarea (not only input bar, needs line breaks)
- Rules sort
- Allow Players Who Are In Queue
- Max Spectators
- Hero Limit
- Hide Max Team 1/2 Players / Max FFA Players in DeathMatch only ect. 
- Hide default value in lobby

**Comment by blockout22** [comment]
I've added most of the requests 

Nodes:

- [x] Modify Player Score - Added
- [x] Set Player Allowed Heroes - Added
- [x] Filtered Array - Added
- [x] Skip If - Already exists in If Node
Feature:

Description textarea (not only input bar, needs line breaks)

- [ ] Rules sort - Working on it 

- [x] Allow Players Who Are In Queue - Added
- [x] Max Spectators - Added
- [ ] Hero Limit - **Not Added**
- [ ] Hide Max Team 1/2 Players / Max FFA Players in DeathMatch only ect. - **Not Added**
- [ ] Hide default value in lobby - Not Added

for the features not added I wasn't entirely sure what you were asking for but if it's a feature that would greatly assist users then I would need a little more detail

**Comment by millionart** [comment]
- Skip If (I know 'if' is a better alternative to 'skip if', but 'skip if' is a feature that owws exists and it would be better to just provide it)
- Hero Limit (I may be wrong in my description, but in fact it is the global that is missing from the Modes.)
- Hide Max Team 1/2 Players / Max FFA Players in DeathMatch only ect. (If I create a mode with only individual deathmatch, then it shouldn't have Max Team 1/2 Players, and similarly, there shouldn't be an option for Max FFA Players in team deathmatch either)
- Hide default value in lobby (When a lobby variable is the default value, it is desirable not to display it in Output)
- Compare in Filtered array ( How to write `Set Player Allowed Heroes(Event Player, Filtered Array(All Heroes, Hero Of(Event Player) != Current Array Element));` )
- Inputs has default value (in Player = Event Player ect.)

Thanks for the work, I'm trying to recreate the pieces I already have with it, I'll keep you posted on any problems I run into after that!
Also, can this tool support multiple languages?

**Comment by millionart** [comment]
Here's my little work `8FME1`, you can try to restore it with this tool (100% contrast complete) to see what I'm having trouble with.

**Comment by blockout22** [comment]
> * Skip If (I know 'if' is a better alternative to 'skip if', but 'skip if' is a feature that owws exists and it would be better to just provide it)
> * Hero Limit (I may be wrong in my description, but in fact it is the global that is missing from the Modes.)
> * Hide Max Team 1/2 Players / Max FFA Players in DeathMatch only ect. (If I create a mode with only individual deathmatch, then it shouldn't have Max Team 1/2 Players, and similarly, there shouldn't be an option for Max FFA Players in team deathmatch either)
> * Hide default value in lobby (When a lobby variable is the default value, it is desirable not to display it in Output)
> * Compare in Filtered array ( How to write `Set Player Allowed Heroes(Event Player, Filtered Array(All Heroes, Hero Of(Event Player) != Current Array Element));` )
> * Inputs has default value (in Player = Event Player ect.)
> 
> Thanks for the work, I'm trying to recreate the pieces I already have with it, I'll keep you posted on any problems I run into after that! Also, can this tool support multiple languages?

I might not of been clear enough but the "If" node also contains "Else If", "Skip If" and "Loop If" 
![img2](https://github.com/blockout22/OverwatchVisualScripting/assets/4086993/2c05700e-ba60-4ed3-8acd-68f6e16d8431)

I don't think it affects the game or not whether the default values are in the script or not but it would be interesting to know if it does and why

Below is a preview of how you can do: `Set Player Allowed Heroes(Event Player, Filtered Array(All Heroes, Hero Of(Event Player) != Current Array Element));` although I made a mistake when adding that node and give it the wrong input but that's now fixed and the below image will work


![img1](https://github.com/blockout22/OverwatchVisualScripting/assets/4086993/c342435c-1c45-4318-a33a-805032e00c29)

As for inputs having a default value those are the default values that usually popup when using the official editor ... I'd say it's best having a default value to prevent any errors from happening when pasting the script in game
