### ISSUE TITLE
Bug & feature request

### ISSUE THREAD

**Issue by millionart** [blockout22/OverwatchVisualScripting#3]
Bug
- Copying and pasting nodes seems to produce the wrong results

Feature request
- Undo / redo
- Drag to sort rules

**Comment by blockout22** [comment]
I've fixed the issue with the nodes not correctly copying the ones selected 

just fyi the copy/paste function is a work in progress so it doesn't fully work 

https://github.com/blockout22/OverwatchVisualScripting/commit/2fb1ea13a45f7110ecd33cacfcfa7f416552b46a
