### ISSUE TITLE
QoL Request

### ISSUE THREAD

**Issue by Neuffexx** [blockout22/OverwatchVisualScripting#6]
A simple node that has no connections and simply servers as a comment / grouping indicator.
Think of something similar to what Unreal Engine has, where you can create a node that is always rendered beneath other nodes, that can have a custom colour and a title. (Preferably the title being noticably bigger than a normal node, but not required).

Just to organize the code and make it easier / faster to work with visually.

**Comment by blockout22** [comment]
I'll see if I can implement that 

I do however have comments implemented per node which could also be of use 

![image](https://github.com/blockout22/OverwatchVisualScripting/assets/4086993/eab6bcd4-b278-4299-b365-d95512fd6643)

**Comment by Neuffexx** [comment]
Oh yeah I am already using them, very usueful actually, but what I refer to is using these comment nodes to 'group-comment' certain nodes or multiple node trees at once.
Ie. you have a section of nodes that is dedicated to movement, so you create a group comment around it, assign a colour to it, so when swaping between code you can quickly zoom out and back in to the correct place.

Very useful for large code.

**Comment by blockout22** [comment]
![image](https://github.com/blockout22/OverwatchVisualScripting/assets/4086993/56584e91-a52d-4da7-82bc-97607c9cb868)

took me a while to find this and implement it but I have made progress implementing it

**Comment by Neuffexx** [comment]
Very nice, how does it handle overlap of multiple group comments? As in z-order. Does it know contextually what to render on top based on which node is inside of another or based on oldest/newest created?

**Comment by blockout22** [comment]
![image](https://github.com/blockout22/OverwatchVisualScripting/assets/4086993/da12dded-2e99-4b57-b788-541ee14520a4)

it seems to handle that automatically it's self very well

**Comment by Neuffexx** [comment]
So moving underlying comments around doesn't cause them to be 'moved on top' of others right?
I'm simply asking to avoid the bug of adding / creating comments, and then eventually moving the big one everything sits in and having it suddenly block everything.

If not good job, very nice addition. Will make it massively easier to work with in the long run!

**Comment by blockout22** [comment]
it seems to be working exactly the way you are wanting

**Comment by Neuffexx** [comment]
Tried it, works perfectly, thanks!
