### ISSUE TITLE
Passing Values through If's | Question

### ISSUE THREAD

**Issue by Neuffexx** [blockout22/OverwatchVisualScripting#8]
Not sure if this is the right place for such questions as well.
But I cannot seem to figure out how to pass a value through an If statement?
In this scenario I want to choose the colour for an effect by condition, but how do I get the value from that condition, since the IF only accepts / outputs actions only?
![image](https://github.com/blockout22/OverwatchVisualScripting/assets/63469833/17b7e89d-6c00-4de4-8343-fbe3d8f9b29a)

**Comment by blockout22** [comment]
in Overwatch the green pins are actions 
![image](https://github.com/blockout22/OverwatchVisualScripting/assets/4086993/787fde91-e575-40d6-91ba-13dbf0d104e9)

so you would have to store the color in a variable then use the variable to set the color 

this should work
![image](https://github.com/blockout22/OverwatchVisualScripting/assets/4086993/1491b66a-d99a-458b-ae1c-e1448b656240)

**Comment by Neuffexx** [comment]
Yes, the reason I was asking for this is because I was hoping to avoid the need for more variables.
Since when I originally made the code in workshop it allowed me to nest if statements as such:
![image](https://github.com/blockout22/OverwatchVisualScripting/assets/63469833/8aa4b49f-58fb-42fc-ac2f-5621c54337fc)

Where the output from the IF statement could be any type of information realy, and I used two bools to inform the top level one for example:
![image](https://github.com/blockout22/OverwatchVisualScripting/assets/63469833/55f44e37-4fdd-42da-ad6e-a153c90da3d8)
![image](https://github.com/blockout22/OverwatchVisualScripting/assets/63469833/a3a88d24-cd2f-49d7-a64e-f245381cfa57)
![image](https://github.com/blockout22/OverwatchVisualScripting/assets/63469833/3cf3d469-8854-413e-a0e0-7b58adead73b)

Dont know how hard that would be to change, but allowing that would be a massive help!

**Comment by blockout22** [comment]
ah I think I see what you mean the if can take anything but it seems like I have hard coded the If node and I am expecting the user to use the compare node in the If Condition resulting in the if only returning true or false (If that makes sense)

![image](https://github.com/blockout22/OverwatchVisualScripting/assets/4086993/af048d05-80fd-41ac-97c8-3389d7311382)

I may need to rethink how the If node is implemented and fix it so it works the same way as in the workshop

**Comment by Neuffexx** [comment]
Would be excelent if you could make the If node 'context' dependand (based on what you provide it) although I know thats a lot more work than the current implementation.
For now ill work with the workaround of extra variables, but waiting for this for sure!

**Comment by blockout22** [comment]
![image](https://github.com/blockout22/OverwatchVisualScripting/assets/4086993/87584e42-c7c2-4181-8f66-2963019710a4)

so reworking the If Node this is an example of what might work best, I may simply add a Green Pin to the If node so the user doesn't have to manually add End to it but if I do that then the user wouldn't be able to add an else... 

any thoughts?

**Comment by Neuffexx** [comment]
Hmm, I'm not really sure I understand the `Do something if` node, based on the image alone.

My problem with the current state of the IF node is that whatever the result of the IF condition, the current 'output' is an action.
Now I understand why the IF node has an action output pin, because it itself is a registered action to be executed inside the workshop.
But the `THEN` / `ELSE` outputs of the workshop IF-THEN-ELSE are type independent, it can return practically anything. Or nothing.

Maybe simply adding an output pin, that would be flexible in what it returns, based on what the 'input' pins are would be for the best.
For example:
`IF Variable >= 3 THEN return COLOR:RED ELSE return COLOR:GREEN`, if that makes any sense.

The only problem I see with this is the case of nested IF-THEN-ELSE statements.
Because how do we input one into the other.

**Comment by Neuffexx** [comment]
Maybe when you connect an IF-THEN-ELSE action output pin to the input pin of another, you expose a second (previously hidden) input pin that takes the output of the nested IF-THEN-ELSE?
This is an example of how the Workshop outputs the nested code, if that helps to some extend for ideas of how to do it visually:
https://pastebin.com/L72WKGpb

**Comment by blockout22** [comment]
> Hmm, I'm not really sure I understand the `Do something if` node, based on the image alone.

This is an example of what you would put into the Do Something part of the code 
![image](https://github.com/blockout22/OverwatchVisualScripting/assets/4086993/8d41ffaf-ae2d-4d39-86e1-beaab03c64b2)

> But the THEN / ELSE outputs of the workshop IF-THEN-ELSE are type independent, it can return practically anything. Or nothing.

I'll work on the IF-THEN-ELSE later as that's not an Action (Green Pin) the Else I was referring to is the one show in the image below

![image](https://github.com/blockout22/OverwatchVisualScripting/assets/4086993/f0153126-a8ec-4bd4-b2df-a3e6a2f2c6c1)

If I were to add the Green Pin to the If node and auto handle the End the user would have to make sure they put the Else into the Green Pin on the If Node of the Else might End up After End which might be more confusing as you would expect the else to be outside the IF

![image](https://github.com/blockout22/OverwatchVisualScripting/assets/4086993/934dacd3-611c-4f2b-aef2-d0e41e498e77)

**Comment by Neuffexx** [comment]
Aaah I see, then there was a misunderstanding from my side from the beginning.

You see I treated the IF node as if it were the IF-THEN-ELSE node, not thinking it wasn't implemented yet.
In that case I should probably rephrase what I meant initially. Please add the IF-THEN-ELSE node as practically anything somewhat complex I implement, or just any UI that reads data, heavily relies on this.

The IF node, with the intended usage that you have shown in the above pictures is completely fine and doesn't need to be reworked at all in my opinion.
Because even if the Workshop lets you put anything into it, it still expects some case to compare to actually make use of the action in any sensible way.

Sorry to have made you do unnecessary work.

**Comment by Neuffexx** [comment]
> ![image](https://private-user-images.githubusercontent.com/4086993/340608318-87584e42-c7c2-4181-8f66-2963019710a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MTAxMzEsIm5iZiI6MTcxODcwOTgzMSwicGF0aCI6Ii80MDg2OTkzLzM0MDYwODMxOC04NzU4NGU0Mi1jN2MyLTQxODEtOGY2Ni0yOTYzMDE5NzEwYTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MThUMTEyMzUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmY0NTk0NWQyMTRjZDQ0YmQ2NmQzZWRhZDcwOWMwZmIyMjk3MGRhNGEwYjExOTk5ZDJhYWRiNGY5YTY4MjAzMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.q5H2GfqHARVS-h1p03d455jq7P7xShgisV8IIpEXwjE)
> 
> so reworking the If Node this is an example of what might work best, I may simply add a Green Pin to the If node so the user doesn't have to manually add End to it but if I do that then the user wouldn't be able to add an else...
> 
> any thoughts?

But in regards to this, I think this is a better way than before if it allows you to put the ELSE into it as well.
That's my biggest question regarding this really, how do we add the ELSE and does it require you to separate the IF block into its own action list? If so, would it not be better to create a new node that lets you add pins for IF / ELSE inputs?
Something along this line:
![image](https://github.com/blockout22/OverwatchVisualScripting/assets/63469833/b5154155-b90e-4b42-a8e4-60e25c715d18)


Essentially, you specify the IF conditional, that IF TRUE, triggers the action (or action list) that is input to the conditionals corresponding (singular) action pin.
The node always has an else action pin available.
But also lets you add the ELSE IF inputs to the node, in between the IF and ELSE default pins.

Then when you have FALSE on the first condition it reads the second condition pin (ELSE IF), and if all of these are FALSE it defaults to the always there ELSE pin.

If that makes sense?

**Comment by blockout22** [comment]
here is what I got

![image](https://github.com/blockout22/OverwatchVisualScripting/assets/4086993/2d83b1ed-a370-4ed9-ae5a-e9402751815c)

which will output 

![image](https://github.com/blockout22/OverwatchVisualScripting/assets/4086993/5679c9c5-8788-4ef0-8885-a3e09c84a04e)


I will update the releases and let me know if it's better, ALSO this WILL break some nodes (If, Compare, And, Or) and remove Nodes To Condition as it's not needed

**Comment by Neuffexx** [comment]
Sorry on holidays atm so no access to PC, will do once I am back in a few days.
